import Head from "next/head";

import Start from "../components/Intro/Intro";
import Context from "../context/Context";

import { useContext, useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
    const router = useRouter();
    const { isLoggedIn } = useContext(Context);

    useEffect(() => {
        if (isLoggedIn) {
            router.push("/app");
        }
    }, [isLoggedIn, router]);

    return (
        <>
            <Head>
                <title>Testcase</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Start />
            </main>
        </>
    );
}
